spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/teatro
    username: teatro
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
